name: Minecraft Server
version: 1.0.1
slug: minecraft
description: A Minecraft server addon with Fabric mod loader support
url: https://github.com/sr229/homeassistant-addons
arch:
  - amd64
  - arm64
init: false
startup: application
boot: auto
options:
  java_memory: "4G"
  minecraft_version: "latest"
  server_type: "FABRIC"
schema:
  java_memory: str
  minecraft_version: str
  server_type: str
ports:
  25565/tcp: 25565
map:
  - config:data
ports_description:
  25565/tcp: Minecraft server port
