name: Minecraft Server
version: "1.0.1"
slug: minecraft
description: A Minecraft server addon supporting Vanilla, Fabric, Forge, Paper, and more
url: https://github.com/sr229/homeassistant-addons
arch:
  - amd64
  - arm64
init: false
startup: application
boot: auto
options:
  data_path: /share/minecraft
  java_args: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch"
  minecraft_version: "1.20.1"
  server_type: "FABRIC"
schema:
  data_path: str
  java_args: str
  minecraft_version: str
  server_type: str
map:
  - data_path: /data
ports:
  25565/tcp: 25565
ports_description:
  25565/tcp: Minecraft server port
